
const INSTAGRAM_URL = "https://www.instagram.com/ricksbygabe?igsh=c25mZTRxdmFhbGt4&utm_source=qr";
const intro=document.getElementById("intro"),enterButton=document.getElementById("enterSite"),nav=document.getElementById("nav"),menuButton=document.getElementById("menuButton"),productGrid=document.getElementById("productGrid"),featuredGrid=document.getElementById("featuredGrid"),inventorySummary=document.getElementById("inventorySummary"),searchInput=document.getElementById("searchInput"),modal=document.getElementById("productModal"),modalClose=document.getElementById("modalClose"),modalMainImage=document.getElementById("modalMainImage"),modalThumbs=document.getElementById("modalThumbs"),modalBrand=document.getElementById("modalBrand"),modalName=document.getElementById("modalName"),modalPrice=document.getElementById("modalPrice"),modalSizes=document.getElementById("modalSizes"),modalStatus=document.getElementById("modalStatus"),modalStock=document.getElementById("modalStock"),modalAction=document.getElementById("modalAction");
let activeFilter="all",searchTerm="";
const money=value=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);
function statusLabel(p){if(p.status==="soldout")return"SOLD OUT";if(p.status==="comingsoon")return"COMING SOON";if(p.stock===1)return"ONLY 1 LEFT";return`${p.stock} AVAILABLE`}
function badgeClass(p){return p.status==="soldout"?"soldout":p.status==="comingsoon"?"comingsoon":""}
function actionHtml(p){if(p.status==="soldout")return'<button class="button disabled" disabled>SOLD OUT</button>';if(p.status==="comingsoon")return'<button class="button disabled" disabled>COMING SOON</button>';return`<a class="button button--light" href="${INSTAGRAM_URL}" target="_blank" rel="noopener">SHOP NOW</a>`}
function cardHtml(p,featured=false){return`<article class="${featured?"featured-card":"product-card"}" data-product="${p.id}" tabindex="0"><div class="product-media"><img src="${p.images[0]}" alt="${p.brand} ${p.name}" loading="lazy"><span class="badge ${badgeClass(p)}">${statusLabel(p)}</span></div><div class="card-copy"><div class="card-brand">${p.brand}</div><h3>${p.name}</h3><div class="price-row"><span class="old-price">${money(p.oldPrice)}</span><strong class="sale-price">${money(p.price)}</strong></div>${p.status==="instock"?`<div class="stock-note">${statusLabel(p)}</div>`:""}</div></article>`}
function filteredProducts(){return PRODUCTS.filter(p=>(activeFilter==="all"||p.category===activeFilter)&&`${p.brand} ${p.name} ${p.sizes.join(" ")}`.toLowerCase().includes(searchTerm))}
function bindOpeners(container){container.querySelectorAll("[data-product]").forEach(card=>{const open=()=>openProduct(card.dataset.product);card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")open()})})}
function renderProducts(){const items=filteredProducts();productGrid.innerHTML=items.map(p=>cardHtml(p)).join("");const available=PRODUCTS.filter(p=>p.status==="instock").reduce((sum,p)=>sum+p.stock,0),coming=PRODUCTS.filter(p=>p.status==="comingsoon").length;inventorySummary.textContent=`${available} available now · ${coming} coming soon`;bindOpeners(productGrid)}
function renderFeatured(){const items=PRODUCTS.filter(p=>p.featured&&p.status!=="soldout").slice(0,6);featuredGrid.innerHTML=items.map(p=>cardHtml(p,true)).join("");bindOpeners(featuredGrid)}
function setFilter(filter){activeFilter=filter;document.querySelectorAll(".filter").forEach(b=>b.classList.toggle("active",b.dataset.filter===filter));renderProducts();document.getElementById("inventory").scrollIntoView({behavior:"smooth"});nav.classList.remove("open")}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;modalMainImage.src=p.images[0];modalMainImage.alt=`${p.brand} ${p.name}`;modalBrand.textContent=`${p.brand} · ${p.category.toUpperCase()}`;modalName.textContent=p.name;modalPrice.innerHTML=`<span class="old-price">${money(p.oldPrice)}</span><strong class="sale-price">${money(p.price)}</strong>`;modalSizes.textContent=p.sizes.join(" · ");modalStatus.textContent=statusLabel(p);modalStock.textContent=p.status==="instock"?String(p.stock):"—";modalAction.innerHTML=actionHtml(p);modalThumbs.innerHTML=p.images.map((src,i)=>`<button data-src="${src}" aria-label="View image ${i+1}"><img src="${src}" alt=""></button>`).join("");modalThumbs.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>modalMainImage.src=b.dataset.src));modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("lock")}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("lock")}
enterButton.addEventListener("click",()=>intro.classList.add("hidden"));menuButton.addEventListener("click",()=>nav.classList.toggle("open"));document.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>setFilter(b.dataset.filter)));document.querySelectorAll("[data-scroll]").forEach(b=>b.addEventListener("click",()=>{document.getElementById(b.dataset.scroll).scrollIntoView({behavior:"smooth"});nav.classList.remove("open")}));searchInput.addEventListener("input",e=>{searchTerm=e.target.value.trim().toLowerCase();renderProducts()});modalClose.addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});renderFeatured();renderProducts();
